### ISSUE TITLE
Model generation fails when using custom type

### ISSUE THREAD

**Issue by iron3oxide** [Japan7/edgedb-pydantic-codegen#5]
I have a custom type defined in my schema:
```
scalar type EntryRef extending sequence;
```
which leads to the following error when trying to generate code:
```
  File "/home/jason/.cache/pypoetry/virtualenvs/luisa-NA6DEBba-py3.11/lib/python3.11/site-packages/edgedb_pydantic_codegen/generator.py", line 228, in parse_type
    raise ValueError(f"Unknown type: {type}")
ValueError: Unknown type: ScalarType(desc_id=UUID('a9e46e2a-7dcc-11ee-b701-7b87fa1f3300'), name='default::EntryRef', base_type=BaseScalarType(desc_id=UUID('00000000-0000-0000-0000-000000000105'), name='std::int64'))
```
This error does not occur when using the official codegen where it is simply aliasing `int`.

**Comment by NextFire** [comment]
Hello! I pushed a fix in https://github.com/Japan7/edgedb-pydantic-codegen/tree/fix/scalartype. Can you try it and report me the result?

**Comment by iron3oxide** [comment]
Seems to work fine! Thanks for the quick solution.
