### ISSUE TITLE
[Suggestion] Simplify usage

### ISSUE THREAD

**Issue by iron3oxide** [Japan7/edgedb-pydantic-codegen#7]
When developing an app, your queries and result types may have to be changed on a regular basis. It is a bit tedious to each time

1. type out "python -m edgedb_pydantic_codegen"
2. Remember and type out your queries directory, which may be nested deeply in your project.

I therefore propose to 

1. Change the command name to something short like "epc"
2. Follow the behaviour of the original edgedb codegen feature and by default search for a queries directory in the whole project

What do you think?

**Comment by NextFire** [comment]
Hello!

> type out "python -m edgedb_pydantic_codegen"

> Change the command name to something short like "epc"

In the latest release you can directly call the generator with `edgedb-pydantic-codegen`. I don't like acronym commands, but you can add an alias to your shell if you want a more convenient shortcut.

> Remember and type out your queries directory, which may be nested deeply in your project.

> Follow the behaviour of the original edgedb codegen feature and by default search for a queries directory in the whole project

The directory argument is already processed recursively, you should be able to simply pass your project root. 

As I personally use VS Code, I have also set up a build task in `.vscode/tasks.json` that calls the generator on a specified directory when <kbd>cmd</kbd>+<kbd>b</kbd>. 

Even more conveniently, you may also quickly set something up with `watchfiles` that uses the generator programmatically during development!

**Comment by iron3oxide** [comment]
Thanks for the quick reply! Great to hear that it already works recursively, I guess the way the usage is documented made me believe otherwise. Adding an alias is also a good enough solution for me, so I'll close this.

**Comment by NextFire** [comment]
Oh sure, being foremost an internal tool for us, the generator may currently not fit everyone's use cases and the documentation is clearly lacking at the moment. I'll try to improve it in my spare time!

**Comment by iron3oxide** [comment]
No big deal, it's definitely better than the original codegen already! Quick side note though: I just discovered that passing the project root may not always be advisable as migrations will also be processed (and raise an error). In my case the `dbschema` directory was in the project root, so simply passing the directory containing my python code was enough.
